spring:
  cloud:
    gateway:
      routes:
       - id: r1
         uri: http://localhost:9191
         predicates:
          - Path= /customers/**
      
       - id: r2
         uri: http://localhost:9393
         predicates:
          - Path= /products/**